#BASE IMAGE.
FROM python:3.7-alpine

#TAG THE DOCKERFILE WITH MAINTAINER NAME AND EMAIL.
LABEL NAME="ANUBHAV SIDHU"
LABEL EMAIL="anubhav231989@gmail.com"

#SET ENVIRONMENT VARIABLE PYTHONUNBUFFERED MODE.
ENV PYTHONUNBUFFERED 1

#UPDATE THE BASE IMAGE AND INSTALL THE OS LEVEL PROJECT DEPENDENCIES.
RUN apk update

#COPY THE PROJECT DEPENDENCIES.
COPY ./project-dependencies.txt /project-dependencies.txt

#PIP INSTALL PROJECT DEPENDENCIES.
RUN pip install -r /project-dependencies.txt

#CREATE APPLICATION FOLDER AND SET WORKING DIRECTORY.
RUN mkdir /source
WORKDIR /source

#COPY SOURCE CODE.
COPY ./source /source

#CREATE APPLICATION USER AND SWITCH USER.
RUN adduser -D appuser
USER appuser

#EXPOSE PORTS.

#SPECIFY DEFAULT COMMAND TO RUN.